%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Alexander\Desktop\run_1_pid_tuning.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/05/08 12:27:01

%% Initialize variables.
filename = 'C:\Users\Alexander\Desktop\Master-Thesis-git\Heat Exchanger\run_3_pid_tuning.txt';
delimiter = '\t';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
run1pidtuning = table(dataArray{1:end-1}, 'VariableNames', {'PID','Temp','Time'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;