function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "serialRunOnArduino"};
	this.sidHashMap["serialRunOnArduino"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "serialRunOnArduino:13"};
	this.sidHashMap["serialRunOnArduino:13"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "serialRunOnArduino:32"};
	this.sidHashMap["serialRunOnArduino:32"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/Enabled Subsystem"] = {sid: "serialRunOnArduino:13"};
	this.sidHashMap["serialRunOnArduino:13"] = {rtwname: "<Root>/Enabled Subsystem"};
	this.rtwnameHashMap["<Root>/Serial Receive"] = {sid: "serialRunOnArduino:12"};
	this.sidHashMap["serialRunOnArduino:12"] = {rtwname: "<Root>/Serial Receive"};
	this.rtwnameHashMap["<Root>/Serial Transmit"] = {sid: "serialRunOnArduino:4"};
	this.sidHashMap["serialRunOnArduino:4"] = {rtwname: "<Root>/Serial Transmit"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "serialRunOnArduino:14"};
	this.sidHashMap["serialRunOnArduino:14"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/Enable"] = {sid: "serialRunOnArduino:15"};
	this.sidHashMap["serialRunOnArduino:15"] = {rtwname: "<S1>/Enable"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "serialRunOnArduino:26"};
	this.sidHashMap["serialRunOnArduino:26"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Constant"] = {sid: "serialRunOnArduino:27"};
	this.sidHashMap["serialRunOnArduino:27"] = {rtwname: "<S1>/Constant"};
	this.rtwnameHashMap["<S1>/Discrete-Time Integrator"] = {sid: "serialRunOnArduino:24"};
	this.sidHashMap["serialRunOnArduino:24"] = {rtwname: "<S1>/Discrete-Time Integrator"};
	this.rtwnameHashMap["<S1>/Gain"] = {sid: "serialRunOnArduino:23"};
	this.sidHashMap["serialRunOnArduino:23"] = {rtwname: "<S1>/Gain"};
	this.rtwnameHashMap["<S1>/Gain1"] = {sid: "serialRunOnArduino:28"};
	this.sidHashMap["serialRunOnArduino:28"] = {rtwname: "<S1>/Gain1"};
	this.rtwnameHashMap["<S1>/Subsystem"] = {sid: "serialRunOnArduino:32"};
	this.sidHashMap["serialRunOnArduino:32"] = {rtwname: "<S1>/Subsystem"};
	this.rtwnameHashMap["<S1>/Sum"] = {sid: "serialRunOnArduino:25"};
	this.sidHashMap["serialRunOnArduino:25"] = {rtwname: "<S1>/Sum"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "serialRunOnArduino:16"};
	this.sidHashMap["serialRunOnArduino:16"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>/In1"] = {sid: "serialRunOnArduino:33"};
	this.sidHashMap["serialRunOnArduino:33"] = {rtwname: "<S2>/In1"};
	this.rtwnameHashMap["<S2>/Constant2"] = {sid: "serialRunOnArduino:29"};
	this.sidHashMap["serialRunOnArduino:29"] = {rtwname: "<S2>/Constant2"};
	this.rtwnameHashMap["<S2>/Gain2"] = {sid: "serialRunOnArduino:30"};
	this.sidHashMap["serialRunOnArduino:30"] = {rtwname: "<S2>/Gain2"};
	this.rtwnameHashMap["<S2>/Subtract"] = {sid: "serialRunOnArduino:31"};
	this.sidHashMap["serialRunOnArduino:31"] = {rtwname: "<S2>/Subtract"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "serialRunOnArduino:34"};
	this.sidHashMap["serialRunOnArduino:34"] = {rtwname: "<S2>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
