function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Arduino_pid_program"};
	this.sidHashMap["Arduino_pid_program"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "Arduino_pid_program:13"};
	this.sidHashMap["Arduino_pid_program:13"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Enabled Subsystem"] = {sid: "Arduino_pid_program:13"};
	this.sidHashMap["Arduino_pid_program:13"] = {rtwname: "<Root>/Enabled Subsystem"};
	this.rtwnameHashMap["<Root>/Serial Receive"] = {sid: "Arduino_pid_program:12"};
	this.sidHashMap["Arduino_pid_program:12"] = {rtwname: "<Root>/Serial Receive"};
	this.rtwnameHashMap["<Root>/Serial Transmit"] = {sid: "Arduino_pid_program:4"};
	this.sidHashMap["Arduino_pid_program:4"] = {rtwname: "<Root>/Serial Transmit"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "Arduino_pid_program:14"};
	this.sidHashMap["Arduino_pid_program:14"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/Enable"] = {sid: "Arduino_pid_program:15"};
	this.sidHashMap["Arduino_pid_program:15"] = {rtwname: "<S1>/Enable"};
	this.rtwnameHashMap["<S1>/Add"] = {sid: "Arduino_pid_program:38"};
	this.sidHashMap["Arduino_pid_program:38"] = {rtwname: "<S1>/Add"};
	this.rtwnameHashMap["<S1>/Discrete-Time Integrator"] = {sid: "Arduino_pid_program:52"};
	this.sidHashMap["Arduino_pid_program:52"] = {rtwname: "<S1>/Discrete-Time Integrator"};
	this.rtwnameHashMap["<S1>/Discrete-Time Integrator1"] = {sid: "Arduino_pid_program:53"};
	this.sidHashMap["Arduino_pid_program:53"] = {rtwname: "<S1>/Discrete-Time Integrator1"};
	this.rtwnameHashMap["<S1>/Gain"] = {sid: "Arduino_pid_program:39"};
	this.sidHashMap["Arduino_pid_program:39"] = {rtwname: "<S1>/Gain"};
	this.rtwnameHashMap["<S1>/Gain1"] = {sid: "Arduino_pid_program:40"};
	this.sidHashMap["Arduino_pid_program:40"] = {rtwname: "<S1>/Gain1"};
	this.rtwnameHashMap["<S1>/Gain2"] = {sid: "Arduino_pid_program:41"};
	this.sidHashMap["Arduino_pid_program:41"] = {rtwname: "<S1>/Gain2"};
	this.rtwnameHashMap["<S1>/Gain3"] = {sid: "Arduino_pid_program:42"};
	this.sidHashMap["Arduino_pid_program:42"] = {rtwname: "<S1>/Gain3"};
	this.rtwnameHashMap["<S1>/Gain4"] = {sid: "Arduino_pid_program:43"};
	this.sidHashMap["Arduino_pid_program:43"] = {rtwname: "<S1>/Gain4"};
	this.rtwnameHashMap["<S1>/Saturation"] = {sid: "Arduino_pid_program:46"};
	this.sidHashMap["Arduino_pid_program:46"] = {rtwname: "<S1>/Saturation"};
	this.rtwnameHashMap["<S1>/Sum"] = {sid: "Arduino_pid_program:49"};
	this.sidHashMap["Arduino_pid_program:49"] = {rtwname: "<S1>/Sum"};
	this.rtwnameHashMap["<S1>/Sum1"] = {sid: "Arduino_pid_program:50"};
	this.sidHashMap["Arduino_pid_program:50"] = {rtwname: "<S1>/Sum1"};
	this.rtwnameHashMap["<S1>/Sum2"] = {sid: "Arduino_pid_program:51"};
	this.sidHashMap["Arduino_pid_program:51"] = {rtwname: "<S1>/Sum2"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "Arduino_pid_program:16"};
	this.sidHashMap["Arduino_pid_program:16"] = {rtwname: "<S1>/Out1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
